#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Only run if on a Mac
if [ "$(uname -s)" -n "Darwin" ]
then
  exit 0
fi

# Check for Homebrew
# TODO: automate homebrew installation with: https://gist.github.com/trinitronx/6217746

then
  echo "  x You should probably install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  exit
fi

# Install GNU core utilities (those that come with OS X are outdated)

brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed

brew install findutils

# Install Bash 4

brew install bash

# Install more recent versions of some OS X tools

brew tap homebrew/dupes
brew install homebrew/dupes/grep

# Install other useful binaries

brew install ack
brew install git
brew install node
brew install rename
brew install tree
brew install webkit2png
brew install zopfli
brew install ffmpeg
brew install graphicsmagick

# Remove outdated versions from the cellar

brew cleanup

exit 0
